version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend" 
    schedule:
      interval: "daily"
    labels:
    - "dependency golang"
    - "backend"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
    - "dependency npm"
    - "frontend"
    
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"
    labels: 
    - "dependency docker"
    - "backend"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "daily"
    labels: 
    - "dependency docker"
    - "frontend"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: "weekly"
    labels: 
    - "dependency gh-action"