services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=realworld
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    migrations:
        build:
            context: .
            dockerfile: migrations/Dockerfile
        environment:
            - DATABASE_URL=postgres://postgres:postgres@postgres:5432/realworld
        volumes:
            - ./migrations:/app
        depends_on:
            postgres:
                condition: service_healthy

    realworld:
        build: .
        environment:
            - DATABASE_URL=postgres://postgres:postgres@postgres:5432/realworld
        depends_on:
            postgres:
                condition: service_healthy
            migrations:
                condition: service_completed_successfully
        ports:
            - "3000:3000"

volumes:
    postgres-data:
