version: "3"
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-realworld}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    command: -p 5432
      
  fiber-realworld:
    build: .
    ports:
      - "8585:8585"
    volumes:
      - ./database:/myapp/database
      - ./config:/myapp/config
      - ./.env:/myapp/.env
      - ./config.docker.env:/myapp/config/config.env
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_NAME: ${DB_NAME:-realworld}
      DB_SSLMODE: disable
      PORT: 8585
    restart: on-failure
    networks:
      - app-network
    
  newman-checker:
    image: postman/newman_alpine33
    command: >
      run https://github.com/gothinkster/realworld/raw/main/api/Conduit.postman_collection.json
      --global-var "APIURL=http://fiber-realworld:8585/api"
      --global-var "USERNAME=user2021"
      --global-var "EMAIL=user2021@example.com"
      --global-var "PASSWORD=password"
      --delay-request 500
    depends_on:
      fiber-realworld:
        condition: service_started
    restart: on-failure
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge